apiVersion: v1
kind: Service
metadata:
  name: simpleapi
  namespace: default
spec:
  ports:
  - port: 9001
    targetPort: 9001
    name: http
    protocol: TCP
    nodePort: 30001
  selector:
    app: simpleapi
  type: NodePort
